image: gulp:latest

before_script:
  - npm install
  - bower install --allow-root

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

job1:
  stage: build
  script:
    - gulp build
  only:
    - master
  tags:
    - docker
  artifacts:
    paths:
      - dist/
  cache:
    paths:
    - dist/

job2:
  stage: deploy
  script:
    - 'rsync -vre ssh ./dist/ $REMOTE_URI:~/web/hylinkers.com/demo/dev-utility'
    - 'rsync -vre "ssh -p $LINODE_PORT" --delete --exclude="vendor" ./dist/ $LINODE_URI:/var/www/dev-utility'
