image: webdeskltd/gulp

before_script:
  - npm install
  - bower install --allow-root
  
stages:
  - build
  - test
  - deploy
  
job1:
  stage: build
  script:
    - gulp build
  only:
    - master
  tags:
    - docker