image: webdeskltd/gulp

before_script:
  - npm install
  - bower install --allow-root
  
stages:
  - build
  - deploy
  
job1:
  stage: build
  script:
    - gulp build
  only:
    - master
  tags:
    - docker
    
job2:
  stage: deploy
  script:
    - ls dist