image: webdeskltd/gulp:latest

before_script:
  - npm install
  - bower install --allow-root

stages:
  - build

job:
  stage: build
  script:
    - gulp build
    - 'rsync -vre ssh ./dist/ $REMOTE_URI:~/web/hylinkers.com/demo/dev-utility'
  only:
    - master
  tags:
    - docker
