image: gulp:latest

before_script:
  - npm install
  - bower install --allow-root
  
stages:
  - build
  - deploy
  
job1:
  stage: build
  script:
    - gulp build
    - ls dist
  only:
    - master
  tags:
    - docker
    
job2:
  stage: deploy
  script:
    - gulp build
    - ls dist
    - "sshpass -p $REMOTE_PASSWORD scp -qr dist $REMOTE_URI:/mnt/vdc/web/hylinkers.com/demo/dev-utility"
  tags:
    - scp