image: gulp:latest

before_script:
  - npm install
  - bower install --allow-root
  
job:
  script:
    - gulp build
    - ls dist
    - "echo $REMOTE_URI:/mnt/vdc/web/hylinkers.com/demo/dev-utility"
    - 'sshpass -e scp -qr -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null dist $REMOTE_URI:/mnt/vdc/web/hylinkers.com/demo/dev-utility'
  only:
    - master
  tags:
    - docker
