image: gulp:latest

before_script:
  - npm install
  - bower install --allow-root

stages:
  - build
  - deploy

job:
  stage: build
  script:
    - gulp build
    - mv dist dev-utility
    - 'sshpass -e scp -qr -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null dev-utility $REMOTE_URI:/mnt/vdc/web/hylinkers.com/demo/dev-utility'
  only:
    - master
  tags:
    - docker

test:
  stage: deploy
  script:
    - ls